apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
spec:
  ingressClassName: nginx
  rules:
  - host: springapp.datapandasconsulting.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: springapp
            port:
              number: 80
  - host: mavenapp.datapandasconsulting.com
    http:
      paths:
      - pathType: Prefix
        path: /maven-web-application
        backend:
          service:
            name: mavenwebapp
            port:
              number: 80	
  - host: blue.datapandasconsulting.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: blue
            port:
              number: 80	